"""
make_annotation_task.py - prepare portable Mask Picker task folders/zips.

The package keeps the normal workspace layout:
  images/
  output/<model>/{overlay,npy,png,yolo}/
  selected/
  polygons/
  skipped/
  labels.json
  selections.json
  README_FOR_ANNOTATOR.md

This is intentionally different from the final dataset pack in bake_all.py:
annotation tasks include model predictions so another participant can keep
working without rerunning segmentation.
"""
from __future__ import annotations

import argparse
import json
import math
import shutil
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA_DIR = ROOT / "data" / "vesicles_good"
DEFAULT_OUTPUT_DIR = ROOT / "_send" / "annotation_tasks"
DEFAULT_README = ROOT / "docs" / "README_FOR_ANNOTATOR_VESICLES.md"

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".tif", ".tiff"}
MODEL_FORMAT_EXTS = {
    "overlay": ".png",
    "png": ".png",
    "npy": ".npy",
    "yolo": ".txt",
}

START_BAT = r"""@echo off
chcp 65001 > nul
setlocal EnableExtensions EnableDelayedExpansion

REM Portable launcher generated by make_annotation_task.py.
REM It treats the folder containing this file as the Mask Picker workspace.
set "WORKSPACE=%~dp0"

if defined CRYOBIOLOGY_ROOT (
  set "ROOT=%CRYOBIOLOGY_ROOT%"
  if exist "%ROOT%\apps\mask_picker\app.py" goto found_root
)

set "SEARCH=%WORKSPACE%"
for /L %%I in (0,1,7) do (
  if exist "!SEARCH!apps\mask_picker\app.py" (
    set "ROOT=!SEARCH!"
    goto found_root
  )
  set "SEARCH=!SEARCH!..\"
)

echo.
echo [ERROR] Не нашел корень проекта Cryobiology.
echo.
echo Этот архив содержит workspace с фото и model-output, но для запуска
echo нужен сам проект с apps\mask_picker\app.py и shared\cellsegkit.
echo.
echo Варианты:
echo   1. Распакуй эту папку внутрь или рядом с полной папкой Cryobiology.
echo   2. Или задай переменную CRYOBIOLOGY_ROOT:
echo      set CRYOBIOLOGY_ROOT=C:\path\to\Cryobiology
echo      START_MASK_PICKER.bat
echo.
pause
exit /b 1

:found_root
for %%I in ("%ROOT%.") do set "ROOT=%%~fI"
for %%I in ("%WORKSPACE%.") do set "WORKSPACE=%%~fI"

where python >nul 2>nul
if not errorlevel 1 (
  set "PY=python"
) else (
  where py >nul 2>nul
  if not errorlevel 1 (
    set "PY=py -3"
  ) else (
    echo.
    echo [ERROR] Python не найден. Установи Python 3.10+ и включи Add to PATH.
    echo https://www.python.org/downloads/
    echo.
    pause
    exit /b 1
  )
)

echo [i] Project root: %ROOT%
echo [i] Workspace   : %WORKSPACE%
echo [i] Checking Python dependencies...

set "PYTHONPATH=%ROOT%\shared\cellsegkit;%PYTHONPATH%"

%PY% -c "import flask, yaml, numpy, PIL, cv2, matplotlib, skimage" >nul 2>nul
if errorlevel 1 (
  %PY% -m pip install --user -r "%ROOT%\apps\mask_picker\requirements.txt"
  if errorlevel 1 goto pip_error
)

%PY% -c "import cellsegkit" >nul 2>nul
if errorlevel 1 (
  echo.
  echo [ERROR] Не найден локальный пакет cellsegkit в %ROOT%\shared\cellsegkit
  echo.
  pause
  exit /b 1
)

cd /d "%ROOT%"
%PY% "%ROOT%\apps\mask_picker\app.py" --workspace "%WORKSPACE%"
if errorlevel 1 pause
exit /b %errorlevel%

:pip_error
echo.
echo [ERROR] Не удалось установить зависимости. Проверь интернет, pip и права записи.
echo.
pause
exit /b 1
"""


def normalize_stem(value: str) -> str:
    text = value.strip().strip('"').strip("'")
    if not text:
        return ""
    return Path(text).stem


def read_stem_list(path: Path) -> list[str]:
    stems: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            stems.append(normalize_stem(line))
    return stems


def discover_image_stems(data_dir: Path) -> list[str]:
    images_dir = data_dir / "images"
    if not images_dir.exists():
        raise FileNotFoundError(f"images dir not found: {images_dir}")
    return sorted(
        p.stem for p in images_dir.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS
    )


def resolve_stems(data_dir: Path, args: argparse.Namespace) -> list[str]:
    stems: list[str] = []
    if args.all:
        stems.extend(discover_image_stems(data_dir))
    if args.stems:
        for chunk in args.stems.split(","):
            stem = normalize_stem(chunk)
            if stem:
                stems.append(stem)
    if args.list:
        stems.extend(read_stem_list(args.list))
    if not stems:
        raise ValueError("Choose images with --all, --stems, or --list.")

    known = set(discover_image_stems(data_dir))
    result: list[str] = []
    missing: list[str] = []
    for stem in stems:
        if stem in result:
            continue
        if stem not in known:
            missing.append(stem)
        else:
            result.append(stem)
    if missing:
        raise FileNotFoundError("Unknown image stems: " + ", ".join(missing))
    return result


def chunks(items: list[str], parts: int) -> list[list[str]]:
    if parts <= 1:
        return [items]
    size = math.ceil(len(items) / parts)
    return [items[i:i + size] for i in range(0, len(items), size)]


def copy_file(src: Path, dst: Path) -> bool:
    if not src.exists() or not src.is_file():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return True


def find_image(data_dir: Path, stem: str) -> Path | None:
    for ext in IMAGE_EXTS:
        p = data_dir / "images" / f"{stem}{ext}"
        if p.exists():
            return p
    return None


def filter_selections(data_dir: Path, stems: list[str]) -> dict:
    path = data_dir / "selections.json"
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    wanted = set(stems)
    return {stem: entry for stem, entry in data.items() if stem in wanted}


def filter_cleanup_json(src: Path, stems: list[str], dst: Path) -> int:
    if not src.exists():
        return 0
    data = json.loads(src.read_text(encoding="utf-8"))
    wanted = set(stems)
    filtered = {stem: entry for stem, entry in data.items() if stem in wanted}
    if not filtered:
        return 0
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(json.dumps(filtered, ensure_ascii=False, indent=2), encoding="utf-8")
    return len(filtered)


def copy_selected_tree(data_dir: Path, task_dir: Path, stems: list[str]) -> int:
    selected_root = data_dir / "selected"
    if not selected_root.exists():
        return 0
    copied = 0
    for model_dir in selected_root.iterdir():
        if not model_dir.is_dir() or model_dir.name.startswith("_"):
            continue
        model = model_dir.name
        copied += filter_cleanup_json(
            model_dir / "cleanup.json",
            stems,
            task_dir / "selected" / model / "cleanup.json",
        )
        for fmt, ext in MODEL_FORMAT_EXTS.items():
            for stem in stems:
                if copy_file(
                    model_dir / fmt / f"{stem}{ext}",
                    task_dir / "selected" / model / fmt / f"{stem}{ext}",
                ):
                    copied += 1
    return copied


def copy_model_outputs(data_dir: Path, task_dir: Path, stems: list[str]) -> dict[str, int]:
    output_root = data_dir / "output"
    counts: dict[str, int] = {}
    if not output_root.exists():
        return counts
    for model_dir in sorted(p for p in output_root.iterdir() if p.is_dir()):
        model_count = 0
        for fmt, ext in MODEL_FORMAT_EXTS.items():
            for stem in stems:
                if copy_file(
                    model_dir / fmt / f"{stem}{ext}",
                    task_dir / "output" / model_dir.name / fmt / f"{stem}{ext}",
                ):
                    model_count += 1
        counts[model_dir.name] = model_count
    return counts


def write_readme(task_dir: Path, readme_source: Path | None) -> None:
    dst = task_dir / "README_FOR_ANNOTATOR.md"
    if readme_source and readme_source.exists():
        copy_file(readme_source, dst)
        return
    dst.write_text(
        "# Mask Picker annotation task\n\n"
        "Unpack this folder and run Mask Picker with `--workspace <this-folder>`.\n",
        encoding="utf-8",
    )


def write_start_launcher(task_dir: Path) -> None:
    (task_dir / "START_MASK_PICKER.bat").write_text(START_BAT, encoding="utf-8")


def display_source_path(data_dir: Path) -> str:
    try:
        return str(data_dir.resolve().relative_to(ROOT))
    except ValueError:
        return data_dir.name


def prepare_task(
    data_dir: Path,
    task_dir: Path,
    stems: list[str],
    readme_source: Path | None = DEFAULT_README,
) -> dict:
    if task_dir.exists():
        shutil.rmtree(task_dir)
    for rel in ["images", "output", "selected", "polygons", "skipped"]:
        (task_dir / rel).mkdir(parents=True, exist_ok=True)

    copied_images = 0
    copied_polygons = 0
    copied_skipped = 0
    for stem in stems:
        img = find_image(data_dir, stem)
        if img and copy_file(img, task_dir / "images" / img.name):
            copied_images += 1
        if copy_file(data_dir / "polygons" / f"{stem}.json", task_dir / "polygons" / f"{stem}.json"):
            copied_polygons += 1
        if copy_file(data_dir / "skipped" / f"{stem}.skipped.txt", task_dir / "skipped" / f"{stem}.skipped.txt"):
            copied_skipped += 1

    labels_path = data_dir / "labels.json"
    if labels_path.exists():
        copy_file(labels_path, task_dir / "labels.json")
    (task_dir / "selections.json").write_text(
        json.dumps(filter_selections(data_dir, stems), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    output_counts = copy_model_outputs(data_dir, task_dir, stems)
    selected_count = copy_selected_tree(data_dir, task_dir, stems)
    write_readme(task_dir, readme_source)
    write_start_launcher(task_dir)

    manifest = {
        "task_name": task_dir.name,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "source_data_dir": display_source_path(data_dir),
        "stems": stems,
        "counts": {
            "images": copied_images,
            "polygons": copied_polygons,
            "skipped_markers": copied_skipped,
            "selected_files": selected_count,
            "output_files_by_model": output_counts,
        },
        "usage": {
            "run": "Double-click START_MASK_PICKER.bat, or run python apps/mask_picker/app.py --workspace <task-folder> from the project root.",
            "export_results": "Use the Export button in Mask Picker or return selected/, polygons/, selections.json.",
            "final_bake": "python tools/launchers/bake_all.py --data-dir <task-folder> --pack",
        },
    }
    (task_dir / "MANIFEST.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return manifest


def zip_dir(task_dir: Path, zip_path: Path) -> Path:
    if zip_path.exists():
        zip_path.unlink()
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6, allowZip64=True) as zf:
        for path in sorted(task_dir.rglob("*")):
            if path.is_file():
                zf.write(path, task_dir.name / path.relative_to(task_dir))
    return zip_path


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Prepare portable Mask Picker annotation task packages.")
    p.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR,
                   help="Workspace/data dir with images and output model predictions.")
    p.add_argument("--name", default=None,
                   help="Task name. Default: annotation_<data-dir-name>.")
    p.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR,
                   help="Where task folders/zips are written.")
    p.add_argument("--all", action="store_true", help="Include all images from images/.")
    p.add_argument("--stems", default=None,
                   help="Comma-separated stems or filenames, e.g. db_img_0084,db_img_0169.jpg.")
    p.add_argument("--list", type=Path, default=None,
                   help="Text file with one stem/filename per line. # comments are allowed.")
    p.add_argument("--parts", type=int, default=1,
                   help="Split selected stems into N separate task packages.")
    p.add_argument("--no-zip", action="store_true",
                   help="Only write folders, do not create zip files.")
    p.add_argument("--readme", type=Path, default=DEFAULT_README,
                   help="README copied into each task folder.")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    data_dir = args.data_dir.resolve()
    output_dir = args.output_dir.resolve()
    task_name = args.name or f"annotation_{data_dir.name}"

    try:
        stems = resolve_stems(data_dir, args)
        part_groups = chunks(stems, max(1, args.parts))
    except Exception as exc:
        print(f"[!] {exc}", file=sys.stderr)
        return 2

    output_dir.mkdir(parents=True, exist_ok=True)
    for idx, part_stems in enumerate(part_groups, 1):
        suffix = "" if len(part_groups) == 1 else f"_part{idx:02d}_of_{len(part_groups):02d}"
        task_dir = output_dir / f"{task_name}{suffix}"
        manifest = prepare_task(data_dir, task_dir, part_stems, args.readme)
        print(f"[task] {task_dir} - {len(part_stems)} images")
        for model, count in manifest["counts"]["output_files_by_model"].items():
            print(f"       {model}: {count} output files")
        if not args.no_zip:
            zip_path = zip_dir(task_dir, task_dir.with_suffix(".zip"))
            print(f"[zip]  {zip_path} ({zip_path.stat().st_size / 1024 / 1024:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
